### ISSUE TITLE
inconsistency in message language

### ISSUE THREAD

**Issue by jordandc20** [learn-co-curriculum/phase-0-completing-assignments-codegrade#5]
### Canvas Link

https://learning.flatironschool.com/courses/6611/assignments/224886?module_item_id=525442

### Concern

Hi! there seems to be a discrepancy between the video and the text description. The video states that the convention is to not to write message descriptions in the tense like "created"  but instead should say "creates" . in the written instructions it uses "created myfile.md". it would be nice if these were consistent

**Comment by jlboba** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students.

We appreciate your support! 💙
